- bin/nfxstat.h
Hi there,
I discovered the file `nfxstat.h` didn't have a header guard, so here's a PR that includes one.
> Add header guard to nfxstat

- bin/nf_common.c
- man/nfdump.1
when post-processing nfdump's output it is quite wasteful to first have nfdump produce iso8601-like strings and then having to parse them back into seconds since the unix epoch.
i've added %trr, %tsr and %ter (analogues to %tr, %ts and %te) which produce fractional seconds for their respective timestamps; the man page was updated.
> added output formats for timestamps in raw format

- bin/nfstat.c
Some sources of data, e.g.  ASA NSEL, record a bidirectional flow record
with separate counters for in/out bytes and in/out packets.  This patch
makes aggregation over "packets", "bytes", "bps" etc look at the *sum* of
the input and output counters.  Previously they would use only the input
counters.
Query types which explicitly look at one direction, like "ibyte" and
"obyte", are unchanged.
Processing of unidirectional flows is not affected, because these store
values in the "in" counters only - the "out" counters are zero, so using the
sum of in+out is the same.
The resulting code is simpler: it doesn't have to calculate both in/out
values everywhere. It also uses accessor functions for all values, which
means no special cases for `r->counter[cindex]`.
> Aggregate using in+out bytes for bidirectional flows

- bin/nfdump.c
Summary often contains large numbers that are hard to read on first sight. This patch enables scaling also on summary numeric values by default: 
Summary: total flows: 211, total bytes: 614.1 M, total packets: 6.9 M, avg bps: 16.4 M, avg pps: 23142, avg bpp: 88
Exact numbers are provided with -N option:
Summary: total flows: 211, total bytes: 614119114, total packets: 6913837, avg bps: 16444975, avg pps: 23142, avg bpp: 88
> Scale numeric values in summary unless -N is used.

- bin/nfcapd.c
nfcapd takes the -M command line parameter and
refers to it in error messages but does not
document it in the usage message. Fix this. #138
> Document -M in usage for nfcapd

- bin/netflow_v5_v7.c
Fix for always outputs input=0, output=0, src_as=0 and dst_as=0 in case of nfreplay -v 5.
> Fix v5_output_record

- bin/output_json.c
I noticed that the bgp6_next_hop output in the json output is incorrectly using bgp4_next_hop for it's key.
> Fixed typo with bgp6_next_hop

- man/nfdump.1
Reported to Debian BTS by Christoph Biedl, see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909437
> Fix typo in nfdump.1

- configure.ac
Fix crossbuilding by using AC_COMPILE_IFELSE instead of AC_RUN_IFELSE
Reported by Helmut Grohe on the Debian BTS at
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948039
I have no idea about the merits of this patch, but Helmut is usually right
> Fix crossbuilding by using AC_COMPILE_IFELSE instead of AC_RUN_IFELSE

- bin/pcaproc.c
I have a tun device running an openconnect VPN. 
The link type is DLT_RAW so it gets raw IP packets that can be process by nfpcapd with this modification. Shouldn't break anything.
> Allow processing of DLT_RAW links (i.e. for a tun VPN)

- bin/Makefile.am
When building nfdump with slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --tag=CC --mode=link clang -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -o nfcapd nfcapd-nfcapd.o nfcapd-nfstatfile.o nfcapd-launch.o nfcapd-nfnet.o nfcapd-collector.o nfcapd-netflow_v1.o nfcapd-netflow_v5_v7.o nfcapd-netflow_v9.o nfcapd-ipfix.o nfcapd-bookkeeper.o nfcapd-expire.o -lnfdump -lresolv -lbz2
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/nfdump/bin"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 34, .st_ino = 19180}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3. …
```
> bin: Use the libtool archives to link.

- Makefile.am
Per autoconf docs [0], if using automake and AC_CONFIG_MACRO_DIR,
we need to include ACLOCAL_AMFLAGS in Makefile.am.
So, let's set ACLOCAL_AMFLAGS = -I m4.
This sorts out an automake warning.
Signed-off-by: Sam James <sam@gentoo.org>
> Makefile.am: add ACLOCAL_AMFLAGS

- configure.ac
This backports the lex change (from da6f37f6abb0cab0cefd6888ebda8e92f0f8903a in the 1.7 series) to 1.6. It is necessary to build on Debian Bookworm.
> Fix build error on Debian 12

- src/output/output_fmt.c
This fix issue with raw output format milliseconds.
1999 ms would incorrectly be converted to "1.099"
(Accidentally found this when looking for root cause of changed msecs in json format, a change in alpine package)
> fix String_LastSeenRaw ms formatting

- configure.ac
The configure script assumes `AC_ARG_ENABLE` set is only triggered with `--enable-xxxx`. This breaks when `--disable-xxxx` is used. Removing handling from `AC_ARG_ENABLE` and checking `$enable_xxxx` directly fixes this issue.
There are some other cases where `AC_ARG_ENABLE` is setting a custom variable. These were left unchanged and may have the same issue if using hard-coded `yes` values instead of `$enableval`.
> Fix ./configure --disable-xxxx handling.

- src/inline/nffile_inline.c
This is a trivial bug introduced in
222419364892155de294792a262cca5e27d41993
> Don't clear flowStartMilliseconds when flowEndMilliseconds==0

- src/nfdump/nfdump.c
- src/nfdump/nfstat.c
- src/output/output.c
- src/output/output.h
- src/output/output_json.c
- src/output/output_json.h
This basically does the same thing as PR #478 does but in what I think is a cleaner way.   This implementation keeps all of the JSON output in the one file and just allows you to choose between variations in white space between records and fields.
I can't get my version to compile on master but I think that is due to the ongoing work for ja3/ja4.  I have an alternate implementation that is working against 1.7.4.
The gist of the differences between json and json-log formats is that json prints out a human readable version of a JSON array of objects.   The "json-log" format is more designed for log processors such as logstash, fluent-bit and things like that.   This format presents one record per line where each line is a wholly contained JSON document rather than the whole output being one …
> Alternate JSON implementation adding json-log output format

- src/nfdump/nflowcache.c
There is no protection against division by zero in aggregation mode (`-A`) for order by pps/bps which leads to `Floating point exception`.
> fix zero division issue in aggregation mode

- src/output/output_json.c
> output_json: Fix observationDoaminID typo in json output.

- src/tor/updateTorDB.sh
Hi,
The script was only able to download data for one month using ./updateTorDB.sh 1. Any attempt to specify a higher value failed because the backward counting mechanism was broken. The issue was due to a missing `-1` in the sequence loop. It needed to be changed from:
`$(seq $n 0)`
to
`$(seq $n -1 0)`
BR
Takalele
> fixed updateTorDB.sh

- src/sflow/sfcapd.c
- src/sflow/sflow_nfdump.c
- src/sflow/sflow_nfdump.h
- src/sflow/sflow_process.c
- src/sflow/sflow_process.h
[Generic Routing Encapsulation (GRE)](https://en.wikipedia.org/wiki/Generic_Routing_Encapsulation) is a tunneling protocol that allows to encapsulate data of various protocols (most prominently Ethernet and IP) in IP packets. For example, an Ethernet frame encapsulated in an IP packet would lead to the following overall header structure:
```
Outer Ethernet header | Outer IP header | GRE header | Encapsulated Ethernet frame
```
Alternatively, it is also possible to encapsulate pure IP packets only, using the following header structure:
```
Outer Ethernet header | Outer IP header | GRE header | Encapsulated IP packet
```
Most relevantly, the GRE header includes a field for the protocol type of the encapsulated protocol, which uses the [EtherType](https://en.wikipedia.org/wiki/EtherType) …
> GRE tunnel introspection for sFlow

- src/output/output_json.c
All JSON fields should have a comma delimiter. This is done by NDJSON but some of the JSON fields seem to be missing this comma.
> Add missing delimiter for JSON output

- src/libnfdump/filter/grammar.y
- src/libnfdump/ssl/ssl.c
- src/libnfdump/ssl/ssl.h
- src/output/output_csv.c
- src/output/output_fmt.c
Fix version for SSL 2.0 and remove version for SSL 1.0, porting FoxIO-LLC/ja4#150, a bug fix made in the JA4 spec in August 2024.  While here, also fix some versions mentioned in strings to match the code.
SSL 2.0 ([draft spec](https://www-archive.mozilla.org/projects/security/pki/nss/ssl/draft02.html)) ([draft rfc](https://datatracker.ietf.org/doc/html/draft-hickman-netscape-ssl-00)) uses a version field of 0x0002, not 0x0200.  SSL 1 never existed outside of Netscape, as the original design was iterated upon to become SSL 2 before the first public version of SSL.  I don't think it's public knowledge what the version field for SSL 1.0 looked like, or if it even was two bytes large or at the same offset on the wire.
Version field 0x0100, that nfdump is currently misattributing to SSL 1.0, …
> Fix wrong SSL 2.0 version and remove SSL 1.0 (bug in older JA4 spec)
